### ISSUE TITLE
Integration Error

### ISSUE THREAD

**Issue by srinathganesh1** [premium-minds/flowable-keycloak#1]
Updated with latest status (removed some irreverent things):

`modules/flowable-ui-modeler/flowable-ui-modeler-conf/src/main/java/org/flowable/ui/modeler/conf/SecurityConfiguration.java`
(I was not able to directly replace the class name, since new class name had one extra parameter)
![Security Configuration](https://user-images.githubusercontent.com/11017158/78022732-1214ae80-7373-11ea-8188-f31e0d27beb2.png)

`modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/flowable-default.properties`
![flowable default properties](https://user-images.githubusercontent.com/11017158/78022834-41c3b680-7373-11ea-8d8e-1a5ab84885b9.png)

User Permission
![user perm](https://user-images.githubusercontent.com/11017158/78022856-4b4d1e80-7373-11ea-91b8-a7adf854ab03.png)

Service Account
![service account](https://user-images.githubusercontent.com/11017158/78022883-530cc300-7373-11ea-97b7-c55ab9003d76.png)

I had to add view-users from the auto generated master-realm to do away with token error
![service acc 2](https://user-images.githubusercontent.com/11017158/78022944-6881ed00-7373-11ea-9501-372029b980b3.png)

Error after signin (there are no logs generated for this in flowable and keycloak)
![Screenshot from 2020-03-31 16-48-29](https://user-images.githubusercontent.com/11017158/78022976-76d00900-7373-11ea-8b4d-f3c845388ff6.png)

**Comment by ajcamilo** [comment]
Your client setup in keycloak needs to have:
*  `Service Accounts` enabled
* The `view-users` and `view-groups` scopes in both client scopes and service account scopes.

I can detail more what to do if you want.

**Comment by srinathganesh1** [comment]
I tried setting the scope and service account, and a few more configs. It still didn't work. Updated original post (since 403 stopped coming somehow)

Do you have a sample demo project? or a sample configuration for keycloak

**Comment by srinathganesh1** [comment]
Update: I made this change

![Screenshot from 2020-03-30 23-50-40](https://user-images.githubusercontent.com/11017158/77947280-55264180-72e1-11ea-938d-8abcf0c0fbf2.png)

**and I am getting error**
![Screenshot from 2020-03-30 23-50-55](https://user-images.githubusercontent.com/11017158/77947309-5d7e7c80-72e1-11ea-9aa4-1f720171b94b.png)

**Comment by ajcamilo** [comment]
Can you show me the logs from keycloak?

**Comment by srinathganesh1** [comment]
> Can you show me the logs from keycloak?

sure will post them.

**Comment by srinathganesh1** [comment]
I will shortly update the original post will all my configuration again (instead of two comments)

---

**Flowable Logs**
```
2020-03-31 16:46:20.360  INFO 19732 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/flowable-modeler]        : Initializing Spring FrameworkServlet 'dispatcherServlet'
2020-03-31 16:46:20.360  INFO 19732 --- [nio-8080-exec-5] o.s.w.s.DispatcherServlet                : FrameworkServlet 'dispatcherServlet': initialization started
2020-03-31 16:46:20.408  INFO 19732 --- [nio-8080-exec-5] o.s.w.s.DispatcherServlet                : FrameworkServlet 'dispatcherServlet': initialization completed in 43 ms
```

**Keycloak Logs**: Nothing getting logged.

![Screenshot from 2020-03-31 16-48-29](https://user-images.githubusercontent.com/11017158/78020656-77ff3700-736f-11ea-9e13-a22ef3600c03.png)

**Comment by srinathganesh1** [comment]
I have updated original post with the latest configs https://github.com/premium-minds/flowable-keycloak/issues/1#issue-585720922

**Comment by ajcamilo** [comment]
I'll make a sample project from https://github.com/flowable/flowable-engine/tree/master/modules/flowable-ui-modeler.

But it will take some time. Maybe next week. Sorry.

**Comment by srinathganesh1** [comment]
> I'll make a sample project from https://github.com/flowable/flowable-engine/tree/master/modules/flowable-ui-modeler.
> 
> But it will take some time. Maybe next week. Sorry.

Ok thank you. does my current configs looks fine?

**Comment by ajcamilo** [comment]
Yes, it looks fine. Maybe there's something missing in the `SecurityConfiguration`. But I need some time to test this.

**Comment by srinathganesh1** [comment]
> Yes, it looks fine. Maybe there's something missing in the `SecurityConfiguration`. But I need some time to test this.

Ok thanks

**Comment by ajcamilo** [comment]
@srinathganesh1 can you checkout this commit: https://github.com/premium-minds/flowable-keycloak-example/commit/69dda8c4fb92d9e0c68d766eafeebbaf11a59036

This example is working for `flowable-ui-modeler`.

**Comment by srinathganesh1** [comment]
Thanks a lot. I will try it out.

**Comment by krishnakumar-ls** [comment]
@ajcamilo @srinathganesh1 Is this issue fixed?
I got the same issue - RESTEASY003210: Could not find resource for full path: http://localhost:8080/flowable-task

**Comment by ajcamilo** [comment]
@krishnakumar-ls I've only did the modifications in the project flowable-ui-modeler, but if you need for the other projects, just do the same changes from this commit: https://github.com/premium-minds/flowable-keycloak-example/commit/69dda8c4fb92d9e0c68d766eafeebbaf11a59036?

**Comment by krishnakumar-ls** [comment]
@ajcamilo I did the changes in flowable-task project as per this commit https://github.com/premium-minds/flowable-keycloak-example/commit/69dda8c4fb92d9e0c68d766eafeebbaf11a59036 
But still I got the same issue(RESTEASY003210: Could not find resource for full path).

![Screen Shot 2020-08-07 at 8 58 13 AM](https://user-images.githubusercontent.com/69308025/89605930-6a613d00-d88c-11ea-9f05-f5705c1750c9.png)
![Screen Shot 2020-08-07 at 8 58 41 AM](https://user-images.githubusercontent.com/69308025/89605937-6e8d5a80-d88c-11ea-81cf-4a1109cffb2a.png)
![Screen Shot 2020-08-07 at 8 59 02 AM](https://user-images.githubusercontent.com/69308025/89605943-71884b00-d88c-11ea-95f0-c46b3d959b01.png)
![Screen Shot 2020-08-07 at 8 59 24 AM](https://user-images.githubusercontent.com/69308025/89605948-73eaa500-d88c-11ea-80d4-57d5fa2b90b3.png)

**Comment by ajcamilo** [comment]
I'll try to get some time in the weekend to check that out, ok?

**Comment by krishnakumar-ls** [comment]
@ajcamilo Sure.

**Comment by ajcamilo** [comment]
@krishnakumar-ls what is the version of flowable you are using?

**Comment by krishnakumar-ls** [comment]
@ajcamilo I'm using Flowable 6.5.0

**Comment by krishnakumar-ls** [comment]
@ajcamilo Got 404 error for the URL 'http://localhost:8080/flowable-task/' after redirect from keycloak auth server.

![Screen Shot 2020-08-10 at 4 42 41 PM](https://user-images.githubusercontent.com/69308025/89777200-df50a300-db28-11ea-94a2-b5f06cc66bd4.png)
![Screen Shot 2020-08-10 at 4 46 30 PM](https://user-images.githubusercontent.com/69308025/89777322-16bf4f80-db29-11ea-9d5f-fc2b73878543.png)

**Comment by ajcamilo** [comment]
Sorry for the delay @krishnakumar-ls 

Checkout the new version of https://github.com/premium-minds/flowable-keycloak-example/commit/9d1314a3be5d9f02889eb61c093c1a5a95e9c522

Now flowable-task uses keycloak authentication.

![Screenshot from 2020-08-12 14-30-46](https://user-images.githubusercontent.com/4998021/90021438-2cf41980-dca9-11ea-8b4a-c1a70fac6aea.png)

**Comment by krishnakumar-ls** [comment]
@ajcamilo Thank you! I will try this checkout https://github.com/premium-minds/flowable-keycloak-example/commit/9d1314a3be5d9f02889eb61c093c1a5a95e9c522
Can you you share me the configuration changes in flowable-ui-*-app>src>main>docker>docker-compose.yml to build a flowable docker image.

**Comment by ajcamilo** [comment]
add the following to the `environment` part of the flowable app:

```
      - KEYCLOAK_URL=<url to keycloak>
      - KEYCLOAK_REALM=<keycloak realm>
      - KEYCLOAK_ISSUER-URL=<issuer url>
      - KEYCLOAK_CLIENT_CLIENT-ID=<client id>
      - KEYCLOAK_CLIENT_CLIENT-SECRET=<client secret>
```

**Comment by Sanlisi** [comment]
@srinathganesh1 hi, have you solved your problem?

**Comment by Sanlisi** [comment]
@ajcamilo hi,  I have a problem , when I run flowable-ui-modeler project there is an error in the program,can you tell me the reason？ thank you .

> 
Caused by: java.lang.ClassNotFoundException: com.premiumminds.flowable.conf.KeycloakProperties
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
	at org.springframework.boot.devtools.restart.classloader.RestartClassLoader.loadClass(RestartClassLoader.java:144) ~[spring-boot-devtools-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_161]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_161]
	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:1.8.0_161]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463) ~[spring-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	... 26 more


Process finished with exit code 0

**Comment by ajcamilo** [comment]
@Sanlisi, did you check this out? https://github.com/premium-minds/flowable-keycloak-example

You can see this commit https://github.com/premium-minds/flowable-keycloak-example/commit/69dda8c4fb92d9e0c68d766eafeebbaf11a59036
It has all the changes needed to the flowable project for the modeler to work with keycloak.

**Comment by Sanlisi** [comment]
@ajcamilo  hi, yesterday’s problem has been solved, but when I access: "localhost:8888/flowable-modeler"，the following error occurred，
------
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Sat Oct 10 09:42:06 CST 2020
There was an unexpected error (type=Internal Server Error, status=500).
javax.ws.rs.ForbiddenException: **HTTP 403 Forbidden**
com.google.common.util.concurrent.UncheckedExecutionException: javax.ws.rs.ForbiddenException: HTTP 403 Forbidden
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.premiumminds.flowable.service.KeycloakServiceImpl.getUser(KeycloakServiceImpl.java:154)
	at com.premiumminds.flowable.filter.AuthenticationHandler.authenticationCallbackHandler(AuthenticationHandler.java:115)
	at com.premiumminds.flowable.filter.KeycloakCookieFilter.doFilterInternal(KeycloakCookieFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ws.rs.ForbiddenException: HTTP 403 Forbidden
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:223)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:195)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:62)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:151)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy154.toRepresentation(Unknown Source)
	at com.premiumminds.flowable.service.KeycloakServiceImpl$1.load(KeycloakServiceImpl.java:90)
	at com.premiumminds.flowable.service.KeycloakServiceImpl$1.load(KeycloakServiceImpl.java:86)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 57 more
-------
so , I have some questions:
1. can you give me some images of keycloak  ui ?
2.  What does mean of  “The view-users and view-groups scopes in both client scopes and service account scopes.” ? and where to set up it ? ------
3.  keycloak.client.scope = openid roles   ------ Where to set up openid roles?

thank you.

**Comment by krishnakumar-ls** [comment]
@Sanlisi This exception is raised due to user permission issue. You have to add client service account roles by click client -> select 'Service Account Roles' tab -> Add client roles
& have to add client role mapping by click user -> select 'Role Mapping' -> add client roles

**Comment by Sanlisi** [comment]
@krishnakumar-ls  @ajcamilo  Sorry, I tried your method, but it still doesn’t work，so can you give me a complete images of 
   keycloak ui ?
 Currently my configuration is like this
![image](https://user-images.githubusercontent.com/29689913/95743091-c2208800-0cc3-11eb-91e8-2e46ff939118.png)
![image](https://user-images.githubusercontent.com/29689913/95743142-d795b200-0cc3-11eb-8a64-9871879410d0.png)

Can you give me your email? thank you very much

**Comment by ajcamilo** [comment]
@Sanlisi the `view-users` and `view-groups` roles are from the client `realm-management`

![Screenshot from 2020-10-12 14-01-40](https://user-images.githubusercontent.com/4998021/95749560-a7361f80-0c93-11eb-9764-3f8aea5bb949.png)

![Screenshot from 2020-10-12 14-02-25](https://user-images.githubusercontent.com/4998021/95749571-ab623d00-0c93-11eb-9d2e-ec3a3d779e29.png)

**Comment by Sanlisi** [comment]
@ajcamilo @srinathganesh1   hi , according to your prompt,  yesterday’s problem has been solved, but I encountered a new problem，when I visit the page：http://localhost:8888/flowable-modeler, as if the page has been refreshing，Why is that？
Where does Kaycloak UI need to be configured? thank you very much。

![image](https://user-images.githubusercontent.com/29689913/95812420-ede55180-0d47-11eb-93c0-f76063b7d544.png)

**Comment by srinathganesh1** [comment]
Sorry to jump the topic in a different direction (still related to keycloak SSO)

I have not personally tried it, but based on release notes it seems latest flowable has built in keycloak support
- Ref: https://blog.flowable.org/2020/10/12/flowable-6-6-0-release/
- Quote: "Support for OAuth2 authentication is added to the Flowable UI App, with Keycloak as an example implementation."

**Comment by Sanlisi** [comment]
@srinathganesh1 @ajcamilo the problem has been solved，I use the 6.6 version，Ref: https://blog.flowable.org/2020/10/12/flowable-6-6-0-release/ ，thank you very much
