### ISSUE TITLE
com.nimbusds library issue

### ISSUE THREAD

**Issue by krishnakumar-ls** [premium-minds/flowable-keycloak#30]
Got following issue while getting authentication from keycloak auth server,

Caused by: java.lang.NoSuchMethodError: com.nimbusds.jwt.JWTClaimsSet.getJSONObjectClaim(Ljava/lang/String;)Lnet/minidev/json/JSONObject;
at com.premiumminds.flowable.service.KeycloakAccessTokenExtractor.getRoles(KeycloakAccessTokenExtractor.java:77) ~[flowable-keycloak-1.5.jar:?]
at com.premiumminds.flowable.service.KeycloakAccessTokenExtractor.getRoles(KeycloakAccessTokenExtractor.java:71) ~[flowable-keycloak-1.5.jar:?]
at com.premiumminds.flowable.filter.AuthenticationHandler.authenticationCallbackHandler(AuthenticationHandler.java:117) ~[flowable-keycloak-1.5.jar:?]
at com.premiumminds.flowable.filter.KeycloakCookieFilter.doFilterInternal(KeycloakCookieFilter.java:108) ~[flowable-keycloak-1.5.jar:?]

**Comment by krishnakumar-ls** [comment]
Got following issue while getting authentication from keycloak auth server,

Caused by: java.lang.NoSuchMethodError: com.nimbusds.jwt.JWTClaimsSet.getJSONObjectClaim(Ljava/lang/String;)Lnet/minidev/json/JSONObject;
	at com.premiumminds.flowable.service.KeycloakAccessTokenExtractor.getRoles(KeycloakAccessTokenExtractor.java:77) ~[flowable-keycloak-1.5.jar:?]
	at com.premiumminds.flowable.service.KeycloakAccessTokenExtractor.getRoles(KeycloakAccessTokenExtractor.java:71) ~[flowable-keycloak-1.5.jar:?]
	at com.premiumminds.flowable.filter.AuthenticationHandler.authenticationCallbackHandler(AuthenticationHandler.java:117) ~[flowable-keycloak-1.5.jar:?]
	at com.premiumminds.flowable.filter.KeycloakCookieFilter.doFilterInternal(KeycloakCookieFilter.java:108) ~[flowable-keycloak-1.5.jar:?]

**Comment by krishnakumar-ls** [comment]
@ajcamilo can you look at this issue?

**Comment by ajcamilo** [comment]
I can't replicate this problem. Can you give me more context?

**Comment by krishnakumar-ls** [comment]
@ajcamilo This issue is resolved for me :)
